
version: 2

sources:
    - name: staging
      #For bigquery:
      database: dtc-de-course-379502

      # For postgres:
      # database: production

      schema: trips_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: external_green_tripdata
        - name: external_yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}
